name: myapp
description: "App Controle Financeiro Multi-perfil."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.3
  
  # Data & Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Backend
  supabase_flutter: ^2.8.4
  dio: ^5.4.0
  
  # DI
  get_it: ^9.0.5
  
  # Utils
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  uuid: ^4.1.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  
  assets:
    - .env